### ISSUE TITLE
ValueError: non-broadcastable output operand with shape () doesn't match the broadcast shape (10,768)

### ISSUE THREAD

**Issue by ScottishFold007** [openweb-ai/thematic#6]
Hello! Thank you very much for providing such a good python library, I have such an error in the process of running, please help me look at it, thank you!
```
params = [{
      "threshold": 0.75,
      "min_community_size": 15,
      "init_max_size": 1000,
        }]

multi_cluster = MultiResCommunityDetection(params)
multi_cluster.fit(sentence_embeddings)
```
The following error message is reported：  

ValueError: non-broadcastable output operand with shape () doesn't match the broadcast shape (10,768)

**Comment by eterna2** [comment]
Hey thanks for raising the ticket. 

Actually the repo is not ready for public usage yet. We need quite a bit more time to write more tests, and formalize our approach before we will be releasing to pypi.

I have pushed a fix to fix the current critical bugs. U can try it out at #7
